const dummyData = {
  teamsData: [
    {
      teamId: 1,
      teamName: "Ski1",
      description: "description1",
      teamProfileUrl: "teamProfileUrl1",
      rating: 4.5,
      instructors: [1, 2, 3],
      teamImages: [
        {
          teamImageId: 1,
          imageUrl: "imageUrl1",
        },
        {
          teamImageId: 2,
          imageUrl: "imageUrl2",
        },
      ],
      cost: 100000,
      basicFee: 10000,
      peopleOptionFee: 10000,
      designatedFee: 10000,
      levelOptionFee: 10000,
      lessonType: "SKI",
      reviewCount: 3,
      reviews: [
        {
          reviewId: 1,
          rating: 4.5,
          content: "content1",
          createdAt: "2023-12-01",
          instructorTags: [
            {
              tagReviewId: 1,
              tagName: "tagName1",
            },
          ],
        },
      ],
    },
    {
      teamId: 2,
      teamName: "Ski2",
      description: "description2",
      teamProfileUrl: "teamProfileUrl2",
      rating: 4.0,
      instructors: [4, 5, 6],
      teamImages: [
        {
          teamImageId: 3,
          imageUrl: "imageUrl3",
        },
        {
          teamImageId: 4,
          imageUrl: "imageUrl4",
        },
      ],
      cost: 200000,
      basicFee: 20000,
      peopleOptionFee: 20000,
      designatedFee: 20000,
      levelOptionFee: 20000,
      lessonType: "SNOWBOARD",
      reviewCount: 5,
      reviews: [
        {
          reviewId: 2,
          rating: 4.0,
          content: "content2",
          createdAt: "2023-11-01",
          instructorTags: [
            {
              tagReviewId: 2,
              tagName: "tagName2",
            },
          ],
        },
      ],
    },
    {
      teamId: 3,
      teamName: "Ski3",
      description: "description3",
      teamProfileUrl: "teamProfileUrl3",
      rating: 4.8,
      instructors: [7, 8, 9],
      teamImages: [
        {
          teamImageId: 5,
          imageUrl: "imageUrl5",
        },
        {
          teamImageId: 6,
          imageUrl: "imageUrl6",
        },
      ],
      cost: 150000,
      basicFee: 15000,
      peopleOptionFee: 15000,
      designatedFee: 15000,
      levelOptionFee: 15000,
      lessonType: "SKI",
      reviewCount: 4,
      reviews: [
        {
          reviewId: 3,
          rating: 4.8,
          content: "content3",
          createdAt: "2023-10-01",
          instructorTags: [
            {
              tagReviewId: 3,
              tagName: "tagName3",
            },
          ],
        },
      ],
    },
  ],
  beginnerInstructorsData: [
    {
      instructorId: 1,
      userName: "instructor1",
      teamId: 1,
      teamName: "team1",
      position: "position1",
      description: "description1",
      instructorUrl: "instructorUrl1",
      gender: "MALE",
      certificateInfo: [
        {
          certificateId: 1,
          certificateName: "certificateName1",
          certificateType: "certificateType1",
          certificateImageUrl: "certificateImageUrl1",
        },
        {
          certificateId: 2,
          certificateName: "certificateName2",
          certificateType: "certificateType2",
          certificateImageUrl: "certificateImageUrl2",
        },
      ],
      rating: 4.5,
      reviewCount: 3,
      cost: 100000,
      basicFee: 10000,
      peopleOptionFee: 10000,
      designatedFee: 10000,
      levelOptionFee: 10000,
      lessonType: "SKI",
      reviews: [
        {
          reviewId: 1,
          rating: 4.5,
          content: "content1",
          createdAt: "2023-12-01",
          instructorTags: [
            {
              tagReviewId: 1,
              tagName: "tagName1",
            },
          ],
        },
      ],
    },
    {
      instructorId: 2,
      userName: "instructor2",
      teamId: 1,
      teamName: "team1",
      position: "position2",
      description: "description2",
      instructorUrl: "instructorUrl2",
      gender: "FEMALE",
      certificateInfo: [
        {
          certificateId: 3,
          certificateName: "certificateName3",
          certificateType: "certificateType3",
          certificateImageUrl: "certificateImageUrl3",
        },
        {
          certificateId: 4,
          certificateName: "certificateName4",
          certificateType: "certificateType4",
          certificateImageUrl: "certificateImageUrl4",
        },
      ],
      rating: 4.2,
      reviewCount: 5,
      cost: 110000,
      basicFee: 11000,
      peopleOptionFee: 11000,
      designatedFee: 11000,
      levelOptionFee: 11000,
      lessonType: "SNOWBOARD",
      reviews: [
        {
          reviewId: 2,
          rating: 4.2,
          content: "content2",
          createdAt: "2023-11-01",
          instructorTags: [
            {
              tagReviewId: 2,
              tagName: "tagName2",
            },
          ],
        },
      ],
    },
    {
      instructorId: 3,
      userName: "instructor3",
      teamId: 2,
      teamName: "team2",
      position: "position3",
      description: "description3",
      instructorUrl: "instructorUrl3",
      gender: "MALE",
      certificateInfo: [
        {
          certificateId: 5,
          certificateName: "certificateName5",
          certificateType: "certificateType5",
          certificateImageUrl: "certificateImageUrl5",
        },
        {
          certificateId: 6,
          certificateName: "certificateName6",
          certificateType: "certificateType6",
          certificateImageUrl: "certificateImageUrl6",
        },
      ],
      rating: 4.7,
      reviewCount: 4,
      cost: 120000,
      basicFee: 12000,
      peopleOptionFee: 12000,
      designatedFee: 12000,
      levelOptionFee: 12000,
      lessonType: "SKI",
      reviews: [
        {
          reviewId: 3,
          rating: 4.7,
          content: "content3",
          createdAt: "2023-10-01",
          instructorTags: [
            {
              tagReviewId: 3,
              tagName: "tagName3",
            },
          ],
        },
      ],
    },
  ],
  intermediateInstructorsData: [
    {
      instructorId: 1,
      userName: "instructor2",
      teamId: 2,
      teamName: "team2",
      position: "position2",
      description: "description2",
      instructorUrl: "instructorUrl2",
      gender: "FEMALE",
      certificateInfo: [
        {
          certificateId: 1,
          certificateName: "certificateName2",
          certificateType: "certificateType2",
          certificateImageUrl: "certificateImageUrl2",
        },
        {
          certificateId: 2,
          certificateName: "certificateName2",
          certificateType: "certificateType2",
          certificateImageUrl: "certificateImageUrl2",
        },
      ],
      rating: 4.0,
      reviewCount: 2,
      cost: 90000,
      basicFee: 9000,
      peopleOptionFee: 9000,
      designatedFee: 9000,
      levelOptionFee: 9000,
      lessonType: "SKI",
      reviews: [
        {
          reviewId: 2,
          rating: 4.0,
          content: "content2",
          createdAt: "2023-11-01",
          instructorTags: [
            {
              tagReviewId: 2,
              tagName: "tagName2",
            },
          ],
        },
      ],
    },
    {
      instructorId: 2,
      userName: "instructor4",
      teamId: 3,
      teamName: "team3",
      position: "position3",
      description: "description3",
      instructorUrl: "instructorUrl3",
      gender: "MALE",
      certificateInfo: [
        {
          certificateId: 3,
          certificateName: "certificateName3",
          certificateType: "certificateType3",
          certificateImageUrl: "certificateImageUrl3",
        },
        {
          certificateId: 4,
          certificateName: "certificateName4",
          certificateType: "certificateType4",
          certificateImageUrl: "certificateImageUrl4",
        },
      ],
      rating: 4.3,
      reviewCount: 3,
      cost: 95000,
      basicFee: 9500,
      peopleOptionFee: 9500,
      designatedFee: 9500,
      levelOptionFee: 9500,
      lessonType: "SNOWBOARD",
      reviews: [
        {
          reviewId: 3,
          rating: 4.3,
          content: "content3",
          createdAt: "2023-10-01",
          instructorTags: [
            {
              tagReviewId: 3,
              tagName: "tagName3",
            },
          ],
        },
      ],
    },
    {
      instructorId: 3,
      userName: "instructor5",
      teamId: 4,
      teamName: "team4",
      position: "position4",
      description: "description4",
      instructorUrl: "instructorUrl4",
      gender: "FEMALE",
      certificateInfo: [
        {
          certificateId: 5,
          certificateName: "certificateName5",
          certificateType: "certificateType5",
          certificateImageUrl: "certificateImageUrl5",
        },
        {
          certificateId: 6,
          certificateName: "certificateName6",
          certificateType: "certificateType6",
          certificateImageUrl: "certificateImageUrl6",
        },
      ],
      rating: 4.1,
      reviewCount: 4,
      cost: 100000,
      basicFee: 10000,
      peopleOptionFee: 10000,
      designatedFee: 10000,
      levelOptionFee: 10000,
      lessonType: "SKI",
      reviews: [
        {
          reviewId: 4,
          rating: 4.1,
          content: "content4",
          createdAt: "2023-09-01",
          instructorTags: [
            {
              tagReviewId: 4,
              tagName: "tagName4",
            },
          ],
        },
      ],
    },
  ],

  locationsData: [
    {
      resortId: 1,
      resortName: "용평",
      resortLocation: "강원도 평창군",
      longitude: 128.668,
      latitude: 37.65,
      lessonTime: [1, 2, 3],
    },
    {
      resortId: 2,
      resortName: "평창",
      resortLocation: "강원도 평창군",
      longitude: 128.668,
      latitude: 37.65,
      lessonTime: [3, 5, 6],
    },
    {
      resortId: 3,
      resortName: "강촌",
      resortLocation: "강원도 춘천시",
      longitude: 128.668,
      latitude: 37.65,
      lessonTime: [2, 3, 7],
    },
  ],
};

export default dummyData;
