export const levels = [
    { id: 1, name: "Level1", type: "SKI" },
    { id: 2, name: "Level2", type: "SKI" },
    { id: 3, name: "Level3", type: "SKI" },
    { id: 4, name: "Teaching1", type: "SKI" },
    { id: 5, name: "Teaching2", type: "SKI" },
    { id: 6, name: "Teaching3", type: "SKI" },
    { id: 7, name: "Demonstrator", type: "SKI" },
    { id: 8, name: "Level1", type: "BOARD" },
    { id: 9, name: "Level2", type: "BOARD" },
    { id: 10, name: "Level3", type: "BOARD" },
    { id: 11, name: "Teaching1", type: "BOARD" },
    { id: 12, name: "Teaching2", type: "BOARD" },
    { id: 13, name: "Teaching3", type: "BOARD" },
    { id: 14, name: "Demonstrator", type: "BOARD" },
];
